In [1]:
from warnings import filterwarnings
filterwarnings('ignore')
from sklearn.preprocessing import OneHotEncoder
%matplotlib inline 

import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns 
sns.set_style('darkgrid')

In [2]:
df = pd.read_csv('ML_Input_Model_Train.csv', delimiter=';')
df.tail()

status shortlong  forceIndex  trend2min  trend5min  trend10min  \
4570   GAIN  COMPRADO         100         90        130         120   
4571   GAIN  COMPRADO         140        -50        100         155   
4572   LOSS  COMPRADO         140        165        220         100   
4573   LOSS  COMPRADO          80         20         75          80   
4574   GAIN  COMPRADO          95         15         30          80   

      trend15min  difCand5      buildDate  difOpenClose   dojy  hammer  \
4570          65       100  1573673099000           110  False   False   
4571         255       140  1573673399000           -50  False   False   
4572         120       140  1573673699000           185  False   False   
4573         125        80  1573674299000            50  False   False   
4574          30        95  1573675499000            10  False   False   

      breakout  highGulf  lowGulf  
4570     False     False    False  
4571     False     False    False  
4572     False     False    False  
4573     False     False    False  
4574     False     False    False

In [3]:
print(len(df['shortlong'].unique()))
print(len(df['buildDate'].unique()))

2
4575


In [4]:
df.drop('buildDate', axis=1, inplace=True)
df.tail()

status shortlong  forceIndex  trend2min  trend5min  trend10min  \
4570   GAIN  COMPRADO         100         90        130         120   
4571   GAIN  COMPRADO         140        -50        100         155   
4572   LOSS  COMPRADO         140        165        220         100   
4573   LOSS  COMPRADO          80         20         75          80   
4574   GAIN  COMPRADO          95         15         30          80   

      trend15min  difCand5  difOpenClose   dojy  hammer  breakout  highGulf  \
4570          65       100           110  False   False     False     False   
4571         255       140           -50  False   False     False     False   
4572         120       140           185  False   False     False     False   
4573         125        80            50  False   False     False     False   
4574          30        95            10  False   False     False     False   

      lowGulf  
4570    False  
4571    False  
4572    False  
4573    False  
4574    False

In [5]:
df.columns

Index(['status', 'shortlong', 'forceIndex', 'trend2min', 'trend5min',
       'trend10min', 'trend15min', 'difCand5', 'difOpenClose', 'dojy',
       'hammer', 'breakout', 'highGulf', 'lowGulf'],
      dtype='object')

In [6]:
df['dojy'] = df['dojy'].astype('int')
df['hammer'] = df['hammer'].astype('int')
df['breakout'] = df['breakout'].astype('int') 
df['highGulf'] = df['highGulf'].astype('int') 
df['lowGulf'] = df['lowGulf'].astype('int')

In [7]:
df.tail()

status shortlong  forceIndex  trend2min  trend5min  trend10min  \
4570   GAIN  COMPRADO         100         90        130         120   
4571   GAIN  COMPRADO         140        -50        100         155   
4572   LOSS  COMPRADO         140        165        220         100   
4573   LOSS  COMPRADO          80         20         75          80   
4574   GAIN  COMPRADO          95         15         30          80   

      trend15min  difCand5  difOpenClose  dojy  hammer  breakout  highGulf  \
4570          65       100           110     0       0         0         0   
4571         255       140           -50     0       0         0         0   
4572         120       140           185     0       0         0         0   
4573         125        80            50     0       0         0         0   
4574          30        95            10     0       0         0         0   

      lowGulf  
4570        0  
4571        0  
4572        0  
4573        0  
4574        0

In [8]:
print(df['status'].unique())
print(df['shortlong'].unique())

['GAIN' 'LOSS' 'COMPRADO' 'VENDIDO']
['VENDIDO' 'COMPRADO']


In [9]:
df['status'].replace(to_replace='GAIN', value=1, inplace=True)
df['status'].replace(to_replace='LOSS', value=0, inplace=True)
df['status'].replace(to_replace='COMPRADO', value=2, inplace=True)
df['status'].replace(to_replace='VENDIDO', value=3, inplace=True)

df['shortlong'].replace(to_replace='COMPRADO', value=1, inplace=True)
df['shortlong'].replace(to_replace='VENDIDO', value=0, inplace=True)

In [10]:
df.tail()

status  shortlong  forceIndex  trend2min  trend5min  trend10min  \
4570       1          1         100         90        130         120   
4571       1          1         140        -50        100         155   
4572       0          1         140        165        220         100   
4573       0          1          80         20         75          80   
4574       1          1          95         15         30          80   

      trend15min  difCand5  difOpenClose  dojy  hammer  breakout  highGulf  \
4570          65       100           110     0       0         0         0   
4571         255       140           -50     0       0         0         0   
4572         120       140           185     0       0         0         0   
4573         125        80            50     0       0         0         0   
4574          30        95            10     0       0         0         0   

      lowGulf  
4570        0  
4571        0  
4572        0  
4573        0  
4574        0

In [11]:
X = df.drop('status', axis=1).values
y = df['status'].values

In [12]:
print(X[:5], y[:5])

[[   0   95  -45  -75 -120  -60  -95  -50    0    0    0    0    0]
 [   0  130   15   10   60  -65 -130    0    1    0    0    0    0]
 [   0  105  -60  -15   -5  -85 -105  -60    0    0    0    0    0]
 [   1   85  -40  -10   15   75   85  -25    0    0    0    0    0]
 [   0  120 -125 -175 -140 -185 -120 -100    0    0    0    0    0]] [1 1 0 1 1]


In [13]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

In [14]:
X = StandardScaler().fit_transform(X)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.25)

In [16]:
names = [
    "SVM-LINEAR", "SVM-RBF", "Gaussian Process", "Random Forest",
    "AdaBoost", "Decision Tree"
]

classifiers = [
    LogisticRegression(),
    SVC(kernel="linear"),
    SVC(),
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    AdaBoostClassifier(),
    XGBClassifier()
]

# iterate over classifiers
for name, clf in zip(names, classifiers):
    clf.fit(X_train, y_train)
    score = clf.score(X_test, y_test)
    print(f'{name}: {score}')

SVM-LINEAR: 0.7552447552447552
SVM-RBF: 0.7561188811188811
Gaussian Process: 0.7561188811188811
Random Forest: 0.6092657342657343
AdaBoost: 0.7395104895104895
Decision Tree: 0.6756993006993007


In [32]:
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.utils import to_categorical
from sklearn import metrics

In [39]:
mlp = Sequential()
mlp.add(Dense(100, activation='relu', input_dim=X_train.shape[1]))
mlp.add(Dense(4, activation='sigmoid'))
mlp.compile(loss='categorical_crossentropy', optimizer='adam')
mlp.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_17 (Dense)             (None, 100)               1400      
_________________________________________________________________
dense_18 (Dense)             (None, 4)                 404       
Total params: 1,804
Trainable params: 1,804
Non-trainable params: 0
_________________________________________________________________


In [ ]:
y_train_dummy = to_categorical(y_train)
y_test_dummy = to_categorical(y_test)

mlp.fit(X_train, 
        y_train_dummy, 
        epochs=500,
        verbose=0)

Instructions for updating:
Use tf.cast instead.
